name: CI
on: [push]

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Theme Check
        uses: shopify/theme-check-action@v2
        # You can remove the explicit token input here,
        # as the action will automatically use the GITHUB_TOKEN with set permissions
